### ISSUE TITLE
rmagick deprecated

### ISSUE THREAD

**Issue by jangalinski** [BlackIkeEagle/docker-vimdeck#1]
Hi. Tried this on osx and got: [DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
/usr/lib/ruby/2.3.0/open-uri.rb:37:in `initialize': No such file or directory @ rb_sysopen - img/vim.png (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/open-uri.rb:37:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:37:in `open'

is this not supported anymore?

**Comment by BlackIkeEagle** [comment]
It should work just fine even with the deprecation warning, just tested a minimal presentation with 3 slides and 1 image without issues

**Comment by jangalinski** [comment]
ok, thanks for the quick response ... just wanted to avoid wasting time on something not supposed to work ... will give it another try.

**Comment by BlackIkeEagle** [comment]
I updated the README a bit yesterday, hopefully that helps you too

**Comment by jangalinski** [comment]
It worked for me ... after I read the error message and mapped the right directories. Thanks a lot!
